### ISSUE TITLE
Example to target objects other than Dat gui ? 

### ISSUE THREAD

**Issue by danrossi** [stewdio/THREE.VRController#11]
I can't seem to find an example here to get the controller clicking objects with a raycaster. It for some reason is using Dat gui only. 

Any ideas ?

**Comment by stewdio** [comment]
Hi @danrossi. VRController has no raycasting routines—that’s an additional layer for you (the developer) to add, tuned to your own needs. The DAT GUI (Data Arts Team Graphic User Interface) is one such additional layer that can do this. But if there’s a big want for this functionality to be merged into VRController that might be a fun thing to add.

In the meantime, here’s an example that uses a ton of raycasting to target objects: [Space Rocks](https://spacerocks.moar.io). Check out the [Space Rocks repo](https://github.com/moar-tech/spacerocks). The way it works is that the controller fires [plasma bolts](https://github.com/moar-tech/spacerocks/blob/master/scripts/Bolt.js) and those bolts raycast to see if they are hitting something. [`Bolt.js line 79`](https://github.com/moar-tech/spacerocks/blob/master/scripts/Bolt.js#L79) is where the raycaster test takes place. If that plasma bolt hits a [button](https://github.com/moar-tech/spacerocks/blob/master/scripts/Button.js) then that button’s action gets executed. 

You might also be interested in [`player.js`](https://github.com/moar-tech/spacerocks/blob/master/scripts/player.js) which is what interacts directly with VRController:
[`Line 516`](https://github.com/moar-tech/spacerocks/blob/master/scripts/player.js#L516): Listen for VRController to provide a link to the controller instance.
[`Line 668`](https://github.com/moar-tech/spacerocks/blob/master/scripts/player.js#L668): Check to see if the primary button (trigger) is being pressed.
[`Line 630`](https://github.com/moar-tech/spacerocks/blob/master/scripts/player.js#L630): Request the firing of a plasma bolt from the cannon. (It will fail if a bolt has been fired too recently. Right now I maintain at least 130ms between bolts—that just felt about right.)

And in [`Bolt.js`](https://github.com/moar-tech/spacerocks/blob/master/scripts/Bolt.js):
[`Line 52`](https://github.com/moar-tech/spacerocks/blob/master/scripts/Bolt.js#L52): Apply the controller’s matrix to this bolt so it’s in the correct position, orientation, and scale, ie. emerging from your plasma cannon (the controller).
[`Line 62`](https://github.com/moar-tech/spacerocks/blob/master/scripts/Bolt.js#L62): Set the bolt’s velocity such that it shoots in the correct direction.

**Comment by danrossi** [comment]
Ok thanks for that I tried to decipher what its doing but can't. 

It doesn't need to be built in but on the example. I guess what is needed is a laser line or reticle that moves with the controller object. Which can be used for the Raycaster ?  Much like the native controller in GearVR.

**Comment by danrossi** [comment]
I guess what I am talking about is a demo integration like the original controller in three.js. It uses a laser object to use as the RayCaster. I am just a little not sure how to replicate this controller over. 

https://threejs.org/examples/#webvr_daydream

**Comment by danrossi** [comment]
Possibly ok to close unless a second demo is needed. I kind of have something to work with now. This laser line can be used for intersect. And I guess it will only intersect if the button is pressed.

```
var gamepadHelper = new THREE.Line( new THREE.BufferGeometry(), new THREE.LineBasicMaterial( { linewidth: 4 } ) );
	gamepadHelper.geometry.addAttribute( 'position', new THREE.Float32BufferAttribute( [ 0, 0, 0, 0, 0, - 10 ], 3 ) );

controller.add(gamepadHelper);
```

This adds a line that extends the controller model. The line needs to thin out line the native one does, and it needs to change position when hitting an intersect object.

**Comment by danrossi** [comment]
Here is something on the lines I mentioned. The raycast is hitting just under the object however. I can get it to change colour on button press. 

https://github.com/danrossi/THREE.VRController/blob/master/raycast.html

**Comment by danrossi** [comment]
I've updated the example to reposition the line distance to the intersect object. However it detects an intersect at an offset underneath the box. Any ideas what could cause this in the controller ? Is there an offset that needs to apply to the raycaster ? 

If I direct the line to a region underneath the box it will detect a click and hit properly.

**Comment by danrossi** [comment]
Closing and starting again. I have the raycaster partially working but there is a problem.
